import type { FashionProduct } from './types';

/** Local demo catalog when Supabase catalog is empty or offline */
export const DEMO_PRODUCTS: FashionProduct[] = [
  {
    id: 'demo-syndicate-pink',
    merchant_id: 'demo',
    name: 'AV3YA Syndicate Tracksuit — Neon Pink',
    price: 1899,
    currency: 'ZAR',
    description:
      'Oversized neon pink set with AV3YA Syndicate chest branding and lace-panel track pants. Built to stand apart.',
    image_url: '/products/syndicate-pink-black.png',
    images: ['/products/syndicate-pink-black.png', '/products/syndicate-duo.png'],
    category_name: 'Syndicate',
    sku: 'AV3-SYN-PNK',
    stock_quantity: 12,
    featured: true,
    sizes: [
      { label: 'S', inStock: true },
      { label: 'M', inStock: true },
      { label: 'L', inStock: true },
      { label: 'XL', inStock: true },
    ],
    colors: [{ name: 'Neon Pink', hex: '#ff2d95' }],
    fabric: 'Premium track fabric',
    care_instructions: 'Cold wash inside out. Hang dry.',
    delivery_info: '2-5 business days nationwide.',
    rating: 5,
    review_count: 8,
  },
  {
    id: 'demo-syndicate-black',
    merchant_id: 'demo',
    name: 'AV3YA Syndicate Tracksuit — Black',
    price: 1799,
    currency: 'ZAR',
    description: 'Stealth black Syndicate set with varsity AV3YA branding and leopard side stripe detail.',
    image_url: '/products/syndicate-black-1.png',
    images: ['/products/syndicate-black-1.png', '/products/syndicate-black-2.png'],
    category_name: 'Syndicate',
    sku: 'AV3-SYN-BLK',
    stock_quantity: 16,
    featured: true,
    sizes: [
      { label: 'S', inStock: true },
      { label: 'M', inStock: true },
      { label: 'L', inStock: true },
      { label: 'XL', inStock: false },
    ],
    colors: [{ name: 'Black', hex: '#0a0014' }],
    rating: 4.9,
    review_count: 11,
  },
  {
    id: 'demo-syndicate-blue',
    merchant_id: 'demo',
    name: 'AV3YA Syndicate Tracksuit — Royal Blue',
    price: 1999,
    currency: 'ZAR',
    description: 'Gloss royal blue set with ONE OF A KIND back graphic and lace panel pants.',
    image_url: '/products/syndicate-blue.png',
    images: ['/products/syndicate-blue.png'],
    category_name: 'Syndicate',
    sku: 'AV3-SYN-BLU',
    stock_quantity: 8,
    featured: true,
    sizes: [
      { label: 'M', inStock: true },
      { label: 'L', inStock: true },
      { label: 'XL', inStock: true },
    ],
    colors: [{ name: 'Royal Blue', hex: '#1e4fd9' }],
    rating: 5,
    review_count: 4,
  },
  {
    id: 'demo-paw-set',
    merchant_id: 'demo',
    name: 'AV3YA Paw Hoodie — Cream',
    price: 1299,
    currency: 'ZAR',
    description: 'Faux-fur hood heavyweight zip hoodie with signature paw graphic and geometric chest mark.',
    image_url: '/products/paw-hoodie-cream.png',
    images: ['/products/paw-hoodie-cream.png', '/products/paw-pants-cream.png'],
    category_name: 'Streetwear',
    sku: 'AV3-PAW-HD',
    stock_quantity: 10,
    featured: false,
    sizes: [
      { label: 'S', inStock: true },
      { label: 'M', inStock: true },
      { label: 'L', inStock: true },
    ],
    colors: [{ name: 'Cream', hex: '#f5f0e8' }],
    rating: 4.8,
    review_count: 6,
  },
];
