import type { FashionProduct } from './types';

/** Local demo catalog — shown when Supabase is not yet connected */
export const DEMO_PRODUCTS: FashionProduct[] = [
  {
    id: 'demo-tshirt-1',
    merchant_id: 'demo',
    name: 'Pangolin Classic T-Shirt',
    price: 349,
    currency: 'ZAR',
    description: 'Premium cotton tee featuring the iconic Pangolin logo. Soft, breathable, and built for everyday style.',
    image_url: '/products/tshirt-1.png',
    images: ['/products/tshirt-1.png', '/products/tshirt-2.png', '/products/tshirt-ts.png'],
    category_name: "T-Shirts",
    sku: 'PGN-TS-001',
    stock_quantity: 24,
    featured: true,
    sizes: [
      { label: 'S', inStock: true },
      { label: 'M', inStock: true },
      { label: 'L', inStock: true },
      { label: 'XL', inStock: true },
      { label: 'XXL', inStock: false },
    ],
    colors: [
      { name: 'Cream', hex: '#f5f0e8' },
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Wheat', hex: '#c9a962' },
    ],
    fabric: '100% Premium Cotton',
    care_instructions: 'Machine wash cold. Do not bleach. Tumble dry low.',
    delivery_info: '2-5 business days nationwide. Free delivery on orders over R500.',
    rating: 4.8,
    review_count: 42,
  },
  {
    id: 'demo-tshirt-2',
    merchant_id: 'demo',
    name: 'Pangolin Full Body Tee — Black',
    price: 399,
    currency: 'ZAR',
    description: 'Statement full-body print tee in classic black. A wardrobe essential with bold Pangolin branding.',
    image_url: '/products/tshirt-fullbody-black.png',
    images: ['/products/tshirt-fullbody-black.png', '/products/tshirt-fullbody.png'],
    category_name: "T-Shirts",
    sku: 'PGN-TS-002',
    stock_quantity: 18,
    featured: true,
    sizes: [
      { label: 'S', inStock: true },
      { label: 'M', inStock: true },
      { label: 'L', inStock: true },
      { label: 'XL', inStock: true },
    ],
    colors: [{ name: 'Black', hex: '#0a0a0a' }],
    fabric: '100% Premium Cotton',
    rating: 4.9,
    review_count: 28,
  },
  {
    id: 'demo-color-shirt',
    merchant_id: 'demo',
    name: 'Pangolin Color Block Shirt',
    price: 449,
    currency: 'ZAR',
    description: 'Vibrant color-block design combining Pangolin signature wheat and cream tones.',
    image_url: '/products/color-shirt.png',
    category_name: "Men's Wear",
    sku: 'PGN-SH-001',
    stock_quantity: 12,
    featured: true,
    sizes: [
      { label: 'M', inStock: true },
      { label: 'L', inStock: true },
      { label: 'XL', inStock: true },
    ],
    colors: [
      { name: 'Wheat Mosaic', hex: '#c9a962' },
      { name: 'Cipher', hex: '#6b7c5e' },
    ],
    rating: 4.7,
    review_count: 15,
  },
  {
    id: 'demo-wheat-mosaic',
    merchant_id: 'demo',
    name: 'Wheat Mosaic Collection Set',
    price: 1299,
    currency: 'ZAR',
    description: 'Complete Wheat Mosaic collection — curated pieces for a cohesive seasonal look.',
    image_url: '/collections/wheat-mosaic.jpg',
    category_name: 'Formal Wear',
    sku: 'PGN-SET-001',
    stock_quantity: 8,
    featured: true,
    sizes: [
      { label: 'S', inStock: true },
      { label: 'M', inStock: true },
      { label: 'L', inStock: false },
    ],
    rating: 5.0,
    review_count: 8,
  },
  {
    id: 'demo-cipher',
    merchant_id: 'demo',
    name: 'Cipher Collection Set',
    price: 1199,
    currency: 'ZAR',
    description: 'The Cipher collection — understated elegance with Pangolin craftsmanship.',
    image_url: '/collections/cipher.jpg',
    category_name: 'Formal Wear',
    sku: 'PGN-SET-002',
    stock_quantity: 6,
    featured: false,
    rating: 4.6,
    review_count: 11,
  },
  {
    id: 'demo-stitchwork',
    merchant_id: 'demo',
    name: 'Stitchwork Denim Set',
    price: 1499,
    currency: 'ZAR',
    description: 'Premium stitchwork denim collection. Hand-finished details meet modern silhouettes.',
    image_url: '/collections/stitchwork-denim.jpg',
    category_name: 'Work Wear',
    sku: 'PGN-SET-003',
    stock_quantity: 5,
    featured: true,
    rating: 4.9,
    review_count: 6,
  },
];
